-- Helper function: is_admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'ADMIN'
  );
$$;

-- ============ USERS table ============
CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  prenom TEXT NOT NULL,
  nom TEXT NOT NULL,
  contact TEXT,
  role_id BIGINT REFERENCES public.roles(id) ON DELETE SET NULL,
  service_id BIGINT REFERENCES public.services(id) ON DELETE SET NULL,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT true,
  force_password_change BOOLEAN NOT NULL DEFAULT false,
  password_last_changed TIMESTAMPTZ NOT NULL DEFAULT now(),
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can read users" ON public.users
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Admins can insert users" ON public.users
  FOR INSERT TO authenticated WITH CHECK (public.is_admin());

CREATE POLICY "Admins can update users, users can update self" ON public.users
  FOR UPDATE TO authenticated USING (public.is_admin() OR auth_user_id = auth.uid());

CREATE POLICY "Admins can delete users" ON public.users
  FOR DELETE TO authenticated USING (public.is_admin());

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============ LOGIN ATTEMPTS table ============
CREATE TABLE public.login_attempts (
  username TEXT PRIMARY KEY,
  failed_count INT NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ,
  last_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;

-- Public read so login UI can show countdown before auth
CREATE POLICY "Anyone can read login attempts" ON public.login_attempts
  FOR SELECT USING (true);

CREATE POLICY "Anyone can insert login attempts" ON public.login_attempts
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can update login attempts" ON public.login_attempts
  FOR UPDATE USING (true);

CREATE POLICY "Admins can delete login attempts" ON public.login_attempts
  FOR DELETE TO authenticated USING (public.is_admin());

-- ============ AUDIT LOGS table ============
CREATE TABLE public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID,
  username TEXT,
  action TEXT NOT NULL,
  entity TEXT,
  entity_id TEXT,
  details JSONB,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own logs, admins read all" ON public.audit_logs
  FOR SELECT TO authenticated USING (public.is_admin() OR user_id = auth.uid());

CREATE POLICY "Anyone authenticated can insert own logs" ON public.audit_logs
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid() OR user_id IS NULL);

-- Allow anonymous insert for failed login logging
CREATE POLICY "Anyone can insert anon logs" ON public.audit_logs
  FOR INSERT WITH CHECK (user_id IS NULL);

CREATE INDEX idx_audit_logs_created ON public.audit_logs(created_at DESC);
CREATE INDEX idx_audit_logs_user ON public.audit_logs(user_id);

-- Backfill users from existing profiles + auth.users
INSERT INTO public.users (auth_user_id, prenom, nom, contact, username, email, active, role_id, force_password_change)
SELECT 
  p.id,
  COALESCE(split_part(p.full_name, ' ', 1), p.username),
  COALESCE(NULLIF(substring(p.full_name from position(' ' in p.full_name)+1), ''), ''),
  '',
  p.username,
  u.email,
  true,
  (SELECT id FROM public.roles WHERE nom_role = p.role LIMIT 1),
  false
FROM public.profiles p
JOIN auth.users u ON u.id = p.id
ON CONFLICT (username) DO NOTHING;